<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="0" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-10T21:11:00 EET" name="TutorialsNinja_Project (1)" finished-at="2023-10-10T21:11:39 EET" duration-ms="39298">
    <groups>
    </groups>
    <test started-at="2023-10-10T21:11:00 EET" name="Check Register with Valid Data" finished-at="2023-10-10T21:11:39 EET" duration-ms="39298">
      <class name="TestCases.TC01_Registration">
        <test-method is-config="true" signature="setupChromeDriver(java.lang.String)[pri:0, instance:TestCases.TC01_Registration@5e905f2c]" started-at="2023-10-10T21:11:00 EET" name="setupChromeDriver" finished-at="2023-10-10T21:11:16 EET" duration-ms="16151" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupChromeDriver -->
        <test-method signature="registerNewUser_P()[pri:1, instance:TestCases.TC01_Registration@5e905f2c]" started-at="2023-10-10T21:11:16 EET" name="registerNewUser_P" description="Register with valid data" finished-at="2023-10-10T21:11:29 EET" duration-ms="13129" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.TC01_Registration.registerNewUser_P(TC01_Registration.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUser_P -->
        <test-method is-config="true" signature="quite()[pri:0, instance:TestCases.TC01_Registration@5e905f2c]" started-at="2023-10-10T21:11:29 EET" name="quite" finished-at="2023-10-10T21:11:39 EET" duration-ms="9960" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- TestCases.TC01_Registration -->
    </test> <!-- Check Register with Valid Data -->
  </suite> <!-- TutorialsNinja_Project (1) -->
  <suite started-at="2023-10-10T21:11:39 EET" name="TutorialsNinja_Project (2)" finished-at="2023-10-10T21:12:25 EET" duration-ms="45681">
    <groups>
    </groups>
    <test started-at="2023-10-10T21:11:39 EET" name="Check Register with Valid Data" finished-at="2023-10-10T21:12:25 EET" duration-ms="45681">
      <class name="TestCases.TC01_Registration">
        <test-method is-config="true" signature="setupChromeDriver(java.lang.String)[pri:0, instance:TestCases.TC01_Registration@7b9088f2]" started-at="2023-10-10T21:11:39 EET" name="setupChromeDriver" finished-at="2023-10-10T21:12:00 EET" duration-ms="21075" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupChromeDriver -->
        <test-method signature="registerNewUser_P()[pri:1, instance:TestCases.TC01_Registration@7b9088f2]" started-at="2023-10-10T21:12:00 EET" name="registerNewUser_P" description="Register with valid data" finished-at="2023-10-10T21:12:13 EET" duration-ms="12165" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.TC01_Registration.registerNewUser_P(TC01_Registration.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUser_P -->
        <test-method is-config="true" signature="quite()[pri:0, instance:TestCases.TC01_Registration@7b9088f2]" started-at="2023-10-10T21:12:13 EET" name="quite" finished-at="2023-10-10T21:12:25 EET" duration-ms="12374" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- TestCases.TC01_Registration -->
    </test> <!-- Check Register with Valid Data -->
  </suite> <!-- TutorialsNinja_Project (2) -->
  <suite started-at="2023-10-10T21:12:26 EET" name="TutorialsNinja_Project" finished-at="2023-10-10T21:12:26 EET" duration-ms="0">
    <groups>
    </groups>
  </suite> <!-- TutorialsNinja_Project -->
  <suite started-at="2023-10-10T21:10:15 EET" name="TutorialsNinja_Project (0)" finished-at="2023-10-10T21:10:59 EET" duration-ms="44046">
    <groups>
    </groups>
    <test started-at="2023-10-10T21:10:15 EET" name="Check Register with Valid Data" finished-at="2023-10-10T21:10:59 EET" duration-ms="44046">
      <class name="TestCases.TC01_Registration">
        <test-method is-config="true" signature="setupChromeDriver(java.lang.String)[pri:0, instance:TestCases.TC01_Registration@437ed416]" started-at="2023-10-10T21:10:16 EET" name="setupChromeDriver" finished-at="2023-10-10T21:10:35 EET" duration-ms="18562" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupChromeDriver -->
        <test-method signature="registerNewUser_P()[pri:1, instance:TestCases.TC01_Registration@437ed416]" started-at="2023-10-10T21:10:35 EET" name="registerNewUser_P" description="Register with valid data" finished-at="2023-10-10T21:10:49 EET" duration-ms="13685" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at TestCases.TC01_Registration.registerNewUser_P(TC01_Registration.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- registerNewUser_P -->
        <test-method is-config="true" signature="quite()[pri:0, instance:TestCases.TC01_Registration@437ed416]" started-at="2023-10-10T21:10:50 EET" name="quite" finished-at="2023-10-10T21:10:59 EET" duration-ms="9767" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quite -->
      </class> <!-- TestCases.TC01_Registration -->
    </test> <!-- Check Register with Valid Data -->
  </suite> <!-- TutorialsNinja_Project (0) -->
</testng-results>
